### ISSUE TITLE
modules directory not Available

### ISSUE THREAD

**Issue by chr0n1k** [mhaskar/Octopus#10]
I get the error **[-] modules directory not Available** when interacting with agent and trying to load other PS scripts

![image](https://user-images.githubusercontent.com/30057970/83766118-ac031b00-a684-11ea-9d05-4d06f36ef426.png)

**Comment by mhaskar** [comment]
Thanks for reporting, 

Can you please give me the results of the command `ls`.

Also, Can you please share with me how you started Octopus and from any directory?

Regards.

**Comment by chr0n1k** [comment]
I have Octopus installed in /**opt/Octopus** and started it using **python3 /opt/Octopus/octopus.py**

![image](https://user-images.githubusercontent.com/30057970/83767491-634c6180-a686-11ea-8815-cad86e33b295.png)

Used powershell and hta payloads on the target which both gave the same error.

**Comment by chr0n1k** [comment]
![image](https://user-images.githubusercontent.com/30057970/83768262-3a789c00-a687-11ea-9a71-963ab0637c0a.png)

**Comment by mhaskar** [comment]
Ok, I think I got the problem, when you execute `python3 /opt/Octopus/octopus.py` from outside `/opt/Octopus`, Python will serve `modules` directory from the main directory you executed `python3 /opt/Octopus/octopus.py` from.

To solve this issue, you need to do the following:

* Change the current directory to `/opt/Octopus` using the following command `cd /opt/Octopus`
* Run `python3 Octopus.py`

That should solve the problem.

Please try it and get back to me!

**Comment by chr0n1k** [comment]
It worked. Thanks for clarifying that out.
