### ISSUE TITLE
Listener issues

### ISSUE THREAD

**Issue by etc3p** [mhaskar/Octopus#21]
After several hours of the server listening for new connections, it is not possible to initiate new communication with the C2, the listener must be restarted

**Comment by mhaskar** [comment]
Thank you for submitting the issue @etc3p, we are aware of it and we will release a fix for it soon.

**Comment by uvzz** [comment]
@etc3p @mhaskar   you can fix  it using a  WSGI server such as Tornado or Genvent to run the Flask app,
e.g.

from gevent.pywsgi import WSGIServer
http_server = WSGIServer(('0.0.0.0', port), app, log=None, keyfile=key_path, certfile=cert_path)
http_server.serve_forever()
